FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./ui

CMD ["streamlit", "run", "ui/streamlit_app.py", "--server.port", "8001", "--server.address", "0.0.0.0"]
